Models/ErrorViewModel.cs
using System;

namespace Examen_final.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Participantes_rifa.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Examen_final.Models
{
    public class Participantes_rifa
    {
        public int Id { get; set; }
        public string Telefono { get; set; }
        public string Nombre_completo { get; set; }
        public string DPI { get; set; }
        public string Direccion { get; set; }
        public string Email { get; set; }
    }
}

Controllers/HomeController.cs
using Examen_final.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Examen_final.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/Participantes_rifaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Examen_final.Data;
using Examen_final.Models;

namespace Examen_final.Controllers
{
    public class Participantes_rifaController : Controller
    {
        private readonly Examen_finalContext _context;

        public Participantes_rifaController(Examen_finalContext context)
        {
            _context = context;
        }

        // GET: Participantes_rifa
        public async Task<IActionResult> Index()
        {
            return View(await _context.Participantes_rifa.ToListAsync());
        }

        // GET: Participantes_rifa/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participantes_rifa = await _context.Participantes_rifa
                .FirstOrDefaultAsync(m => m.Id == id);
            if (participantes_rifa == null)
            {
                return NotFound();
            }

            return View(participantes_rifa);
        }

        // GET: Participantes_rifa/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Participantes_rifa/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Telefono,Nombre_completo,DPI,Direccion,Email")] Participantes_rifa participantes_rifa)
        {
            if (ModelState.IsValid)
            {
                _context.Add(participantes_rifa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(participantes_rifa);
        }

        // GET: Participantes_rifa/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participantes_rifa = await _context.Participantes_rifa.FindAsync(id);
            if (participantes_rifa == null)
            {
                return NotFound();
            }
            return View(participantes_rifa);
        }

        // POST: Participantes_rifa/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Telefono,Nombre_completo,DPI,Direccion,Email")] Participantes_rifa participantes_rifa)
        {
            if (id != participantes_rifa.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(participantes_rifa);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Participantes_rifaExists(participantes_rifa.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(participantes_rifa);
        }

        // GET: Participantes_rifa/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participantes_rifa = await _context.Participantes_rifa
                .FirstOrDefaultAsync(m => m.Id == id);
            if (participantes_rifa == null)
            {
                return NotFound();
            }

            return View(participantes_rifa);
        }

        // POST: Participantes_rifa/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var participantes_rifa = await _context.Participantes_rifa.FindAsync(id);
            _context.Participantes_rifa.Remove(participantes_rifa);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Participantes_rifaExists(int id)
        {
            return _context.Participantes_rifa.Any(e => e.Id == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Participantes_rifa/Create.cshtml
@model Examen_final.Models.Participantes_rifa

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Participantes_rifa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre_completo" class="control-label"></label>
                <input asp-for="Nombre_completo" class="form-control" />
                <span asp-validation-for="Nombre_completo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DPI" class="control-label"></label>
                <input asp-for="DPI" class="form-control" />
                <span asp-validation-for="DPI" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Participantes_rifa/Delete.cshtml
@model Examen_final.Models.Participantes_rifa

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Participantes_rifa</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre_completo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre_completo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DPI)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DPI)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Participantes_rifa/Details.cshtml
@model Examen_final.Models.Participantes_rifa

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Participantes_rifa</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre_completo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre_completo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DPI)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DPI)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Participantes_rifa/Edit.cshtml
@model Examen_final.Models.Participantes_rifa

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Participantes_rifa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre_completo" class="control-label"></label>
                <input asp-for="Nombre_completo" class="form-control" />
                <span asp-validation-for="Nombre_completo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DPI" class="control-label"></label>
                <input asp-for="DPI" class="form-control" />
                <span asp-validation-for="DPI" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Participantes_rifa/Index.cshtml
@model IEnumerable<Examen_final.Models.Participantes_rifa>

@{
    ViewData["Title"] = "Index";
}

<h1>Registros</h1>

<p>
    <a asp-action="Create">Crear nuevo registro</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre_completo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DPI)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre_completo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DPI)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Detalles</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Examen_final</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Examen_final</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Participantes_rifa" asp-action="Index">Participantes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Examen_final - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>